[project]
name = "lessons-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "redis>=7.1.0",
    "requests>=2.32.5",
    "schedule>=1.2.2",
]
